apiVersion: v1
kind: Service
metadata:
  name: eks-pet-adoption-linux-service
  namespace: eks-pet-adoption
  labels:
    app: eks-pet-adoption-linux-app
spec:
  selector:
    app: eks-pet-adoption-linux-app
  ports:
    - protocol: TCP
      port: 8011
      targetPort: 8011
  type: LoadBalancer